// Code generated by go test ./internal/thin -update. DO NOT EDIT.

package thin

import "github.com/astralyx/lino/internal/cli"

// Specs describes lino-core's commands.
var Specs = []Spec{
	{Name: "changes", Accept: cli.Accept(3), Local: false, Stdin: false, MinArgs: 0, MaxArgs: 0, Flags: map[string]bool{"path": false, "since": false, "wait": false}},
	{Name: "delete", Accept: cli.Accept(7), Local: false, Stdin: false, MinArgs: 2, MaxArgs: 3, Flags: map[string]bool{"v": false}},
	{Name: "edit", Accept: cli.Accept(7), Local: false, Stdin: true, MinArgs: 2, MaxArgs: 3, Flags: map[string]bool{"v": false}},
	{Name: "help", Accept: cli.Accept(0), Local: true, Stdin: false, MinArgs: 0, MaxArgs: 1, Flags: map[string]bool{"agent": true}},
	{Name: "history", Accept: cli.Accept(3), Local: false, Stdin: false, MinArgs: 0, MaxArgs: 1, Flags: map[string]bool{"by": false, "k": false, "since": false}},
	{Name: "index", Accept: cli.Accept(3), Local: false, Stdin: false, MinArgs: 0, MaxArgs: 0, Flags: map[string]bool{}},
	{Name: "init", Accept: cli.Accept(4), Local: false, Stdin: false, MinArgs: 0, MaxArgs: 1, Flags: map[string]bool{}},
	{Name: "insert", Accept: cli.Accept(7), Local: false, Stdin: true, MinArgs: 1, MaxArgs: 1, Flags: map[string]bool{"after": false, "at-end": true, "at-start": true, "before": false, "v": false}},
	{Name: "ls", Accept: cli.Accept(3), Local: false, Stdin: false, MinArgs: 0, MaxArgs: 1, Flags: map[string]bool{"depth": false}},
	{Name: "mv", Accept: cli.Accept(7), Local: false, Stdin: false, MinArgs: 2, MaxArgs: 2, Flags: map[string]bool{}},
	{Name: "ps", Accept: cli.Accept(0), Local: false, Stdin: false, MinArgs: 0, MaxArgs: 0, Flags: map[string]bool{}},
	{Name: "read", Accept: cli.Accept(3), Local: false, Stdin: false, MinArgs: 1, MaxArgs: 1, Flags: map[string]bool{"anchors": true, "lines": false}},
	{Name: "replace", Accept: cli.Accept(7), Local: false, Stdin: true, MinArgs: 1, MaxArgs: 1, Flags: map[string]bool{"sep": false, "v": false}},
	{Name: "rm", Accept: cli.Accept(7), Local: false, Stdin: false, MinArgs: 1, MaxArgs: 1, Flags: map[string]bool{"force": true, "v": false}},
	{Name: "rollback", Accept: cli.Accept(7), Local: false, Stdin: false, MinArgs: 0, MaxArgs: 1, Flags: map[string]bool{"dry-run": true, "path": false, "to": false}},
	{Name: "run", Accept: cli.Accept(0), Local: true, Stdin: false, MinArgs: 0, MaxArgs: 1, Flags: map[string]bool{"foreground": true, "idle": false, "name": false}},
	{Name: "search", Accept: cli.Accept(3), Local: false, Stdin: false, MinArgs: 1, MaxArgs: -1, Flags: map[string]bool{"C": false, "anchors": true, "k": false, "path": false, "regex": true, "words": true}},
	{Name: "show", Accept: cli.Accept(3), Local: false, Stdin: false, MinArgs: 1, MaxArgs: 1, Flags: map[string]bool{}},
	{Name: "stats", Accept: cli.Accept(3), Local: false, Stdin: false, MinArgs: 0, MaxArgs: 0, Flags: map[string]bool{}},
	{Name: "status", Accept: cli.Accept(1), Local: false, Stdin: false, MinArgs: 0, MaxArgs: 0, Flags: map[string]bool{}},
	{Name: "stop", Accept: cli.Accept(1), Local: true, Stdin: false, MinArgs: 0, MaxArgs: 0, Flags: map[string]bool{}},
	{Name: "write", Accept: cli.Accept(7), Local: false, Stdin: true, MinArgs: 1, MaxArgs: 1, Flags: map[string]bool{"force": true, "v": false}},
}
