package thin_test

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"sort"
	"testing"

	"github.com/astralyx/lino/internal/cli"
	_ "github.com/astralyx/lino/internal/commands"
	"github.com/astralyx/lino/internal/thin"
)

var update = flag.Bool("update", false, "rewrite specs_gen.go from lino-core's commands")

func TestSpecsMatchCore(t *testing.T) {
	want := thin.SpecsOf(cli.Default)
	if *update {
		if err := os.WriteFile("specs_gen.go", gen(t, want), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	if !reflect.DeepEqual(thin.Specs, want) {
		t.Fatal("specs_gen.go is stale: run go test ./internal/thin -update")
	}
}

func gen(t *testing.T, specs []thin.Spec) []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by go test ./internal/thin -update. DO NOT EDIT.\n\npackage thin\n\nimport \"github.com/astralyx/lino/internal/cli\"\n\n")
	b.WriteString("// Specs describes lino-core's commands.\nvar Specs = []Spec{\n")
	for _, s := range specs {
		fmt.Fprintf(&b, "{Name: %q, Accept: cli.Accept(%d), Local: %v, Stdin: %v, MinArgs: %d, MaxArgs: %d, Flags: map[string]bool{",
			s.Name, s.Accept, s.Local, s.Stdin, s.MinArgs, s.MaxArgs)
		names := make([]string, 0, len(s.Flags))
		for n := range s.Flags {
			names = append(names, n)
		}
		sort.Strings(names)
		for _, n := range names {
			fmt.Fprintf(&b, "%q: %v, ", n, s.Flags[n])
		}
		b.WriteString("}},\n")
	}
	b.WriteString("}\n")
	out, err := format.Source(b.Bytes())
	if err != nil {
		t.Fatal(err)
	}
	return out
}
